### ISSUE TITLE
**Error:** Call to a member function getName() on null

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/activity_log#10]
**Error:** Call to a member function getName() on null
**File:** src/addons/activity_log/fragments/filter-form.php
**Line:** 35

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                  | Line     |
| -------------------------------------------- | ----------------------------------------------------- | -------- |
| require                                      | src/core/lib/fragment.php                             | 121      |
| rex_fragment->{closure}                      | src/core/lib/util/timer.php                           | 57       |
| rex_timer::measure                           | src/core/lib/fragment.php                             | 126      |
| rex_fragment->parse                          | src/addons/activity_log/pages/system.activity-log.php | 72       |
| require                                      | src/core/lib/packages/package.php                     | 280      |
| rex_package->includeFile                     | src/core/lib/be/controller.php                        | 482      |
| rex_be_controller::{closure}                 | src/core/lib/util/timer.php                           | 57       |
| rex_timer::measure                           | src/core/lib/be/controller.php                        | 483      |
| rex_be_controller::includePath               | src/core/lib/be/controller.php                        | 432      |
| rex_be_controller::includeCurrentPageSubPath | src/addons/activity_log/pages/index.php               | 7        |
| require                                      | src/core/lib/packages/package.php                     | 280      |
| rex_package->includeFile                     | src/core/lib/be/controller.php                        | 482      |
| rex_be_controller::{closure}                 | src/core/lib/util/timer.php                           | 57       |
| rex_timer::measure                           | src/core/lib/be/controller.php                        | 483      |
| rex_be_controller::includePath               | src/core/lib/be/controller.php                        | 415      |
| rex_be_controller::includeCurrentPage        | src/core/backend.php                                  | 238      |
| require                                      | src/core/boot.php                                     | 143      |
| require                                      | public/redaxo/index.php                               | 12       |

</details>
<details>
<summary>System report (REDAXO 5.13.3, PHP 7.4.30, MariaDB 10.3.34)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.3     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.30     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.3.34 |
| Character set | utf8            |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/15.5 |
|      Protocol | HTTP/1.0    |
|         HTTPS | yes         |

| Packages                |            |
| ----------------------: | :--------- |
|            accessdenied | 2.0.1      |
|            activity_log | 0.0.1      |
|                 adminer | 1.9.2      |
|           animatedlogin | 1.0.0      |
|                  backup | 2.8.1      |
|                be_style | 3.0.2      |
|     be_style/customizer | 3.0.2      |
|         be_style/redaxo | 3.0.2      |
|                 bloecks | 3.1.1      |
|         consent_manager | 2.0.1      |
|                 cropper | 1.3.0      |
|               developer | 3.9.0      |
|         emailobfuscator | 3.0.0      |
|              focuspoint | 4.0.2      |
|         global_settings | 2.8.1      |
|                 install | 2.9.3      |
|                  mblock | 3.1.0      |
|           media_manager | 2.12.3     |
|               mediapool | 2.11.3     |
|                metainfo | 2.8.5      |
|                   mform | 5.3.1      |
|              mform/docs | 1.0        |
|               phpmailer | 2.11.2     |
|                 project | dev        |
|        quick_navigation | 5.4.1      |
|               redactor2 | 4.0.2      |
|               search_it | 6.9.0      |
| search_it/documentation | 6.9.0      |
|                   sprog | 1.3.0      |
|              statistics | 2.2.0      |
|               structure | 2.13.3     |
|       structure/content | 2.13.3     |
|       structure/history | 2.13.3     |
|              theme_lock | 1.0.0      |
|                uploader | 2.3.0      |
|                   users | 2.8.2      |
|                  watson | 2.2.0      |
|                    ycom | 3.0-beta4  |
|               ycom/auth | 3.0-beta4  |
|               ycom/docs | 3.0-beta4  |
|              ycom/group | 3.0-beta4  |
|                   yform | 3.4.2      |
|             yform/email | 3.4.2      |
|           yform/manager | 3.4.2      |
|              yform/rest | 3.4.2      |
|             yform/tools | 3.4.2      |
|         yform_usability | 1.4        |
|             ynewsletter | 1.5        |
|                yrewrite | 2.8.3      |
|             zip_install | 1.2        |

</details>

**Comment by eaCe** [comment]
@skerbis Benutzer in der zwischenzeit gelöscht?

**Comment by skerbis** [comment]
Ja

**Comment by eaCe** [comment]
Dann werde ich auf "User gelöscht" umsteigen, wenn keiner mehr existiert.
