### ISSUE TITLE
unnötige Methode  setConfig()

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/activity_log#11]
die dort gelisteten configs können direkt als defaults in der package.yml notiert werden. Sie werden bei Installation und Update beachtet. 

Siehe z.B. hier: https://github.com/redaxo/redaxo/blob/581d9302ec5afe7344fb2b5c66f338c216b13c05/redaxo/src/addons/phpmailer/package.yml#L26-L48

**Comment by eaCe** [comment]
Danke für den Hinweis. Das wäre vermutlich eleganter.
Gibt es das erst an REDAXO 5.13?

**Comment by skerbis** [comment]
ne schon länger 5.10 / 5.11 da du 5.12 voraussetzt passt es.
