### ISSUE TITLE
Activity Log nur für Admins?

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/activity_log#12]
Ich kann bei User Roles zwar Activity_log unter Allgemein auswählen, der Menüpunkt erscheint aber bei nicht-Admins nicht. 
Redaxo 5.13.3

**Comment by eaCe** [comment]
Ich denke ich habe da einen Fehler in der Config. 
Eigentlich ist dieser nur für Admins gedacht, weiter unten habe ich aber eine Permission. Diese müsste ich entfernen.
https://github.com/FriendsOfREDAXO/activity_log/blob/master/package.yml#L9

**Comment by fietstouring** [comment]
Bekomme einen Error wenn ein nicht-Admin neue Kategorien in einer Mehrsprachigen Redaxo-Installation v 14 anlegen will

Call to a member function getName() on null
…/redaxo/src/addons/activity_log/lib/extension_points/category.php:55

**Comment by eaCe** [comment]
@fietstouring danke. Schau ich mir die Tage an!

**Comment by fietstouring** [comment]
ok danke, ich versuche gerade den Fehler auf meinem lokalen System zu reproduzieren. Am Produktiv-System kam er beim Anlegen einer neuen Subkategorie. Hier kommt jetzt ein neuer Fehler beim Aufruf vom Addon selbst.

```
Call to a member function getName() on null
…/redaxo/src/addons/activity_log/fragments/filter-form.php:35
```

**Comment by eaCe** [comment]
@fietstouring ich kann den Fehler leider aktuell nicht reproduzieren.

**Comment by fietstouring** [comment]
ok, hatte ich schon vermutet, weil er bei mir auch seltsam inkosistent auftritt. muss da nochmal genauer reinschauen.

**Comment by eaCe** [comment]
Ich werde einfach mal eine weitere Abfrage um Category Name hinzufügen. Im Filter scheint der User keinen Namen zu nutzen. Auch hier werde ich Name nutzen, wenn vorhanden, ansonsten den Login. Das ist ein Fehler meinerseits.

**Comment by eaCe** [comment]
->getName könnte wegen einer gelöschten Category Probleme verursachen. Das sollte in der aktuellen Version auch nicht mehr passieren.

**Comment by eaCe** [comment]
Besteht das Problem in der aktuellen Version immer noch?

**Comment by eaCe** [comment]
Ich mach mal zu, wenn es noch Probleme gibt gerne wieder auf machen.
