### ISSUE TITLE
Logeinträge: Undefined index: clang_id

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/activity_log#15]
![image](https://user-images.githubusercontent.com/330560/193123982-f71f5215-2610-4287-8a10-0cc2ae95b2a9.png)

**Affected versions / Verwendete Versionen** activity_log 0.0.1

**Comment by eaCe** [comment]
@aeberhard das sollte in der aktuellen GH-Version bereits behoben sein, siehe:
https://github.com/FriendsOfREDAXO/activity_log/blob/master/lib/extension_points/slice.php#L72
Ich werde am Wochenende die anderen Issues fixen und ein neues Release veröffentlichen.

**Comment by eaCe** [comment]
Besteht das Problem in der aktuellen Version immer noch?

**Comment by aeberhard** [comment]
@eaCe in der github-Version passt das jetzt!

**Comment by eaCe** [comment]
Super, danke dann mach mal zu, wenn es noch Probleme gibt gerne wieder auf machen.
