### ISSUE TITLE
Umgang mit mehreren Parametern

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/activity_log#19]
wie könnte man es lösen, wenn z.B. mehrere Parameter mit rein kommen. Z. B. IP, spezielle IDs, z.B UserID DocumentID, etc., Command, Query, Location etc ..

**Comment by eaCe** [comment]
Man könnte diese natürlich einfach mit Komma getrennt in eine Spalte schreiben. Ich würde nicht für jeden neuen Parameter die Datenbank erweitern. Vielleicht dann auch als JSON in die DB schreiben.

**Comment by eaCe** [comment]
Gerne wieder öffnen, wenn es weiterhin benötigt wird.
