### ISSUE TITLE
Zeit besser vom Server statt DB nehmen und als Zeitzone UTC 

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/activity_log#20]
MySQL Time ist nicht immer = Servertime. Das führte bei mir auch schon mal zu Problemen.

Ich würde keine NOW() oder ähnliche MySQL Zeitfunktionen nehmen und die Zeit vom Server selbst in UTC Zeitzone nehmen. Dann weiß man, dass diese auf allen Umgebungen identisch sind und besser vergleichbar sind. Deswegen wird beim Thema Logs auch immer besonders auf die Einstellung des Zeitservers hingewiesen. In der Ausgabe in REDAXO kann das natürlich entsprechend des Users/Servers ausgegeben werden.

**Comment by eaCe** [comment]
Danke für den Hinweis, das hatte ich nicht auf dem Schirm.
