### ISSUE TITLE
Erweiterung der überwachten EPs

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/activity_log#3]
Sofern es dafür EPs gibt (oder man es anders lösen kann), wäre es toll, wenn noch folgendes mit überwacht werden würde:

- Online/Offline von Artikel & Kategorien
- Arbeitsversion freigeben
- Arbeitsversion leeren
- in Arbeitsversion kopieren
- Slice verschoben
- Addon installiert bzw. geupdated
- Modul/Template hinzugefügt, gelöscht, geupdated

**Comment by eaCe** [comment]
Beim schnellen drüberfliegen konnte ich im Version Addon oder im Installer keine EP's finden.

**Comment by eaCe** [comment]
- [x] Online/Offline von Artikel & Kategorien
- [ ] ~~Arbeitsversion freigeben~~
- [ ] ~~Arbeitsversion leeren~~
- [ ] ~~in Arbeitsversion kopieren~~
- [ ] Slice verschoben
- [ ] Addon installiert bzw. geupdated
- [ ] Modul/Template hinzugefügt, gelöscht, geupdated
