### ISSUE TITLE
Autom. Löschen alter Logs nach x-Tagen

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/activity_log#6]
Eine Option vorsehen, womit man beim Login ins BE alle Logeinträge die älter als X-Tage sind autom. löschen lassen kann.

**Comment by eaCe** [comment]
@iceman-fx es gibt einen Cronjob Eintrag dafür.
Funktioniert natürlich nur wenn man das Addon installiert hat
