### ISSUE TITLE
Fehler bei Update auf aktuelle Version

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/activity_log#9]
Error thrown with message "Call to undefined method rex_activity::setConfig()"

Stacktrace:
#8 Error in /var/www/web199/html/sub_module/redaxo/src/addons/.new.activity_log/update.php:5
#7 require in /var/www/web199/html/sub_module/redaxo/src/core/lib/packages/package.php:280
#6 rex_package:includeFile in /var/www/web199/html/sub_module/redaxo/src/addons/install/lib/package/package_update.php:63
#5 rex_install_package_update:doAction in /var/www/web199/html/sub_module/redaxo/src/addons/install/lib/package/package_download.php:44
#4 rex_install_package_download:run in /var/www/web199/html/sub_module/redaxo/src/addons/install/lib/api/api_package_update.php:21
#3 rex_api_install_package_update:execute in /var/www/web199/html/sub_module/redaxo/src/core/lib/api_function.php:180
#2 rex_api_function:handleCall in /var/www/web199/html/sub_module/redaxo/src/core/backend.php:234
#1 require in /var/www/web199/html/sub_module/redaxo/src/core/boot.php:143
#0 require in /var/www/web199/html/sub_module/redaxo/index.php:9

**Comment by eaCe** [comment]
Schau ich mir an, die Funktion sollte doch eigentlich da sein :/

**Comment by iceman-fx** [comment]
Moin.
In welche update.php soll dies inkludiert werden?
Da gibt es keine update.php.

**Comment by eaCe** [comment]
https://github.com/FriendsOfREDAXO/activity_log/blob/master/update.php
